import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "TaskFlow - Manage Your Tasks Efficiently",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[#FAFAFA]`}
        cz-shortcut-listen="true"
      >
        <QueryProvider>
          <main className="flex flex-col min-h-screen">
            <div className="flex-1 flex-grow">{children}</div>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
