import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import QueryProvider from "@/components/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-[#FAFAFA]`}>
        <QueryProvider>
          <main className="flex flex-col min-h-screen">
            <Navbar />
            <div className="flex-1 flex-grow">{children}</div>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
